version: '3'
services:
    php:
        build:
            context: ./docker
            dockerfile: php.Dockerfile
        container_name: ${APP_NAME:?err}-php
        volumes:
            - './app:/var/www/html'
            - './data/files:/home'
            - '/var/www:/Server'
            - '~/:/Web'
        restart: unless-stopped

   
    nginx:
        image: nginx:latest
        container_name: ${APP_NAME:?err}-nginx
        ports:
            - '800:80'
            - '444:443'
        links:
            - php
        volumes:
            - './app:/var/www/html'
            - './config/nginx:/etc/nginx/conf.d'
            - '~/:/Web'
        restart: unless-stopped
